apiVersion: v1
kind: Pod
metadata:
  name: lab4task4-pod
  labels:
    app: centos
spec:
  containers:
  - name: centos-container
    image: centos
    command: [ "/bin/sh", "-c", "while true; do sleep 3600; done" ]
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task4lab4
  labels:
    app: centos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: lab4-task4-centos
        image: centos
        command: [ "/bin/sh", "-c", "while true; do sleep 3600; done" ]
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab4task4-centos-service
  labels:
    app: centos
spec:
  type: NodePort
  selector:
    app: centos
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30450
